languageCode = "en-us"
title = "Information Technology & Multimedia Security Laboratory"
baseurl = "http://example.org/"
theme = "dimension"

[params]
  title = "ITS Laboratory"
  description = """
  Provides implementation of research results, <br/>
  and softwares used in evaluations.
  """
  logo = "fa-key"
  copyright = "itslab-kyushu"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"
